language: python
python:
  - "2.7"
  - "3.4"

install:
  - "./script/bootstrap --ver=$TRAVIS_PYTHON_VERSION"

# command to run tests
script:
  - py.test tests --doctest-modules --pep8 hypatia -v --cov-report term-missing --cov=hypatia

after_success:
  - coveralls
